# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=1)),
                ('phone', models.IntegerField(blank=True, max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
            ],
        ),
    ]
