# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170913_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('M', 'Males'), ('F', 'Females')], max_length=1),
        ),
    ]
